runtime: go124
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "irmaksuaritmam@gmail.com"
  SMTP_PASS: "znpg ejga sekw bmsw"

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico
    secure: always

  - url: /.*
    script: auto
    secure: always 