version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DOMAIN=yourdomain.com
    volumes:
      - ./data.json:/app/data.json
      - ./orders.json:/app/orders.json
      - ./static/uploads:/app/static/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped
    profiles:
      - production 